<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SerialSimulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SkopiStation.Domain\SkopiStation.Domain.csproj" />
  </ItemGroup>

</Project>
